# Generated by Django 5.0.14 on 2026-09-23 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('rag', '0003_restore_chunk_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagecitation',
            name='source_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='messagecitation',
            name='source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='messagecitation',
            name='chunk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='rag.chunk'),
        ),
        migrations.AlterField(
            model_name='messagecitation',
            name='rank',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='messagecitation',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
