# Generated by Django 5.0.14 on 2026-08-20 08:06

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=512)),
                ('source_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word Document'), ('txt', 'Plain Text'), ('md', 'Markdown'), ('url', 'Web Page')], max_length=8)),
                ('file', models.FileField(blank=True, null=True, upload_to=documents.models.upload_to)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, max_length=2048)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('parsing', 'Parsing'), ('chunking', 'Chunking'), ('embedding', 'Embedding'), ('indexed', 'Indexed'), ('failed', 'Failed')], db_index=True, default='queued', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('embedding_model_name', models.CharField(blank=True, max_length=256)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('chunk_count', models.IntegerField(default=0)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sha256'], name='documents_d_sha256_e75cfc_idx'), models.Index(fields=['status'], name='documents_d_status_07369e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('sha256',), name='unique_document_sha256'),
        ),
    ]
