# Generated by Django 5.0.14 on 2026-08-20 08:10

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        # Must run before any `vector` column is created. Postgres
        # extensions are cluster-wide, so this is a no-op (not an error)
        # if pgvector was already enabled by another app/migration.
        VectorExtension(),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768, null=True)),
                ('content_tsv', models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.SearchVector('content', config='english'), output_field=django.contrib.postgres.search.SearchVectorField())),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('chunk_index', models.IntegerField()),
                ('section_heading', models.CharField(blank=True, max_length=512)),
                ('token_count', models.IntegerField(blank=True, null=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document')),
            ],
            options={
                'ordering': ['document_id', 'chunk_index'],
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='chunk_embedding_hnsw_idx', opclasses=['vector_cosine_ops']), django.contrib.postgres.indexes.GinIndex(fields=['content_tsv'], name='chunk_content_tsv_gin_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='chunk',
            constraint=models.UniqueConstraint(fields=('document', 'chunk_index'), name='unique_chunk_index_per_document'),
        ),
    ]
