# Generated by Django 5.0.14 on 2026-09-04 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chunk',
            name='chunk_embedding_hnsw_idx',
        ),
        migrations.RemoveField(
            model_name='chunk',
            name='embedding',
        ),
    ]
